### ISSUE TITLE
表情

### ISSUE THREAD

**Issue by yuanbin-dev** [yungzhu/rich_input#1]
可不可以实现像微信那种，输入[微笑]后显示微笑图片

**Comment by yungzhu** [comment]
微信是在输入框内显示[微笑]，在展示渲染过程显示图片，这个不属于输入框范畴了

**Comment by yuanbin-dev** [comment]
大佬可以给个demo不，初学这个卡住了

发自我的iPhone

**Comment by yungzhu** [comment]
textspan的children可以接受WidgetSpan,WidgetSpan内可以放图片，进行渲染

同时帮忙star下，感谢

**Comment by yuanbin-dev** [comment]
输入框内部图片可以实现不

**Comment by yungzhu** [comment]
> 输入框内部图片可以实现不

一般在输入框内部显示类似这种 [微笑]

**Comment by yungzhu** [comment]
先关闭了
